export const TOGGLE_LOG_IN = 'TOGGLE_LOG_IN';

export const TOGGLE_LOG_IN_MODAL = 'TOGGLE_LOG_IN_MODAL';

export const TOGGLE_PASSWORD_HIDDEN = 'TOGGLE_PASSWORD_HIDDEN';

export const TOGGLE_TERMS_OF_SERVICE_MODAL = 'TOGGLE_TERMS_OF_SERVICE_MODAL';

export const DISABLE_LOG_IN_MODAL = 'DISABLE_LOG_IN_MODAL';

export const TOGGLE_SIGN_UP_MODAL = 'TOGGLE_SIGN_UP_MODAL';

export const TOGGLE_TERMS_NOT_ACCEPTED = 'TOGGLE_TERMS_NOT_ACCEPTED';

export const TOGGLE_PRIVACY_POLICY_MODAL = 'TOGGLE_PRIVACY_POLICY_MODAL';

export const TOGGLE_INFORMATION_MODAL = 'TOGGLE_INFORMATION_MODAL';

export const TOGGLE_ABOUT_US_MODAL = 'TOGGLE_ABOUT_US_MODAL';

export const TOGGLE_HELP_MODAL = 'TOGGLE_HELP_MODAL';

export const TOGGLE_APP_SETTINGS_MODAL = 'TOGGLE_APP_SETTINGS_MODAL';

export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';

export const TOGGLE_FILTER_MODAL = 'TOGGLE_FILTER_MODAL';

export const UPDATE_SIGN_UP_FIRST_NAME = 'UPDATE_SIGN_UP_FIRST_NAME';

export const UPDATE_SIGN_UP_LAST_NAME = 'UPDATE_SIGN_UP_LAST_NAME';

export const UPDATE_SIGN_UP_EMAIL = 'UPDATE_SIGN_UP_EMAIL';

export const UPDATE_SIGN_UP_PASSWORD = 'UPDATE_SIGN_UP_PASSWORD';

export const UPDATE_LOG_IN_EMAIL = 'UPDATE_LOG_IN_EMAIL';

export const UPDATE_LOG_IN_PASSWORD = 'UPDATE_LOG_IN_PASSWORD';
